apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app-dep
  namespace: practice-dwk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: cluster-share
      containers:
      - name: ping-pong-app
        image: isalxmkh/ping-pong-app:v2.16
        readinessProbe:
          initialDelaySeconds: 10
          httpGet:
            path: /health-db
            port: 4001
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pg-secret
                key: PASSWORD
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config-map
                key: pg_user
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: postgres-config-map
                key: db_name
          - name: DATABASE_URL
            value: postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres-svc/$(POSTGRES_DB)
        volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files/
