apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-app-dep
  namespace: practice-dwk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-app
  template:
    metadata:
      labels:
        app: ping-pong-app
    spec:
      volumes:
        - name: shared-folder
          persistentVolumeClaim:
            claimName: cluster-share
      containers:
      - name: ping-pong-app
        image: isalxmkh/ping-pong-app:v2.01
        volumeMounts:
          - name: shared-folder
            mountPath: /usr/src/app/files/
