apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: practice-dwk
  labels:
    app: postgres
spec:
  ports:
  - port: 5432
    name: pg-port
  clusterIP: None
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: practice-dwk
spec:
  serviceName: postgres-svc
  replicas: 2
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - name: pg-port
              containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /data
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-secret
                  key: PASSWORD
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: pg_user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: db_name
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 100Mi
